### ISSUE TITLE
"SimpleGuide object has no attribute _pos" for guides

### ISSUE THREAD

**Issue by user202729** [spakin/SimpInkScr#128]
1. Create any guide
2. run the following code
 
	```python
	print(guides[0].position)
	```

3. see error:

	```python
	Traceback (most recent call last):
	  File "/SimpInkScr/simpinkscr/simple_inkscape_scripting.py", line 3740, in <module>
		main()
	  File "/SimpInkScr/simpinkscr/simple_inkscape_scripting.py", line 3736, in main
		SimpleInkscapeScripting().run()
	  File "/usr/share/inkscape/extensions/inkex/base.py", line 250, in run
		self.save_raw(self.effect())
					  ^^^^^^^^^^^^^
	  File "/SimpInkScr/simpinkscr/simple_inkscape_scripting.py", line 3729, in effect
		exec(code, _user_globals)
	  File "<string>", line 7, in <module>
	  File "/SimpInkScr/simpinkscr/simple_inkscape_scripting.py", line 1828, in position
		return self._pos
			   ^^^^^^^^^
	AttributeError: 'SimpleGuide' object has no attribute '_pos'
	```

Probably caused by the change in https://github.com/spakin/SimpInkScr/issues/122 .

**Comment by spakin** [comment]
Thanks for the bug report.  I believe this is working now.
