### ISSUE TITLE
Error when trying to insert a newline character using `more_text` function

### ISSUE THREAD

**Issue by ajrou** [spakin/SimpInkScr#15]
I am using the functions `text` and `more_text`  to insert some text. I need to insert a newline as follows:

```
text('Hello, ', (width/2, height/2), font_size='24pt', text_anchor='middle')
more_text('Inkscape', font_weight='bold', fill='#800000')
more_text('!!!')
more_text('\n')
more_text('A new line')
```

But when I run that code, I get the following error:

```
<string> 4 
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ajrou/.local/lib/python3.8/site-packages/pretty_errors/__init__.py", line 683, in excepthook
    writer.write_code(syntax_error_info[0], syntax_error_info[1], [], True, syntax_error_info[2])
  File "/home/ajrou/.local/lib/python3.8/site-packages/pretty_errors/__init__.py", line 572, in write_code
    while start_char > 0 and line[start_char - 1] not in (' ', '\t'):
IndexError: string index out of range

Original exception was:
Traceback (most recent call last):
  File "simple_inkscape_scripting.py", line 779, in <module>
    SimpleInkscapeScripting().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/usr/share/inkscape/extensions/inkex/extensions.py", line 193, in effect
    for child in fragment:
  File "simple_inkscape_scripting.py", line 773, in generate
    exec(code, sis_globals)
  File "<string>", line 4
    more_text('
              ^
SyntaxError: EOL while scanning string literal
```

**Comment by spakin** [comment]
You'll need an extra backslash when entering `\n` in the `Python code` field: `\\n`.  According to [Extensions: INX widgets and parameters](https://wiki.inkscape.org/wiki/Extensions:_INX_widgets_and_parameters),
> Line-breaks will be encoded as literal `\n` in the value passed to the extension.

Hence, Simple Inkscape Scripting replaces all instances of `\n` with a literal newline, and that's why you get an `EOL while scanning string literal` error.

That said, your code still won't work as written.  Newlines aren't honored in SVG `<tspan>` elements (what `more_text` produces).  Instead, you'll need to move explicitly to the next row's coordinates, as in the following restatement of your script:
```Python
from inkex.units import convert_unit

baseline_sep = convert_unit('24pt', 'px')*1.3
text('Hello, ', (width/2, height/2), font_size='24pt', text_anchor='middle')
more_text('Inkscape', font_weight='bold', fill='#800000')
more_text('!!!')
more_text('A new line', (width/2, height/2 + baseline_sep))
```
