### ISSUE TITLE
TypeError: 'SimpleObject' object is not iterable

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#32]
![Screenshot 2022-01-15 135537](https://user-images.githubusercontent.com/140737/149637462-81dc9ede-380c-4ed3-958e-87ad3358bd93.png)

This commit: https://github.com/peterennis/SimpInkScr/commit/994af7033d24da58d3620d87035669d228c8b319

```
Traceback (most recent call last):
  File "C:\Users\peter\AppData\Roaming\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 1545, in <module>
    SimpleInkscapeScripting().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Users\peter\AppData\Roaming\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 1541, in effect
    exec(code, sis_globals)
  File "<string>", line 28, in <module>
  File "C:\Users\peter\AppData\Roaming\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 689, in animate
    self._animate_transforms(all_iobjs, duration,
  File "C:\Users\peter\AppData\Roaming\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 529, in _animate_transforms
    target = group(target)
  File "C:\Users\peter\AppData\Roaming\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 1335, in group
    for o in objs:
TypeError: 'SimpleObject' object is not iterable
```

**Comment by spakin** [comment]
Fixed.  Thanks for the bug report.
