### ISSUE TITLE
Installation test of circle((100, 100), 50) fails

### ISSUE THREAD

**Issue by MachJok** [spakin/SimpInkScr#44]
Installing into the following directory: C:\Program Files\Inkscape\share\inkscape\extensions\SimpInkScr
and then running circle((100, 100), 50) leads to the following error:
`
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 739, in <module>
    SimpleInkscapeScripting().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\extensions.py", line 193, in effect
    for child in fragment:
  File "C:\Program Files\Inkscape\share\inkscape\extensions\SimpInkScr\simple_inkscape_scripting.py", line 725, in generate
    if py_source != '' and not os.path.isdir(py_source):
  File "C:\Program Files\Inkscape\lib\python3.9\genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
`

**Comment by peterennis** [comment]
@MachJok 

Works for me. 
What version of Inkscape?
What version of SimpInkScr?

NOTE: SimpInkScr latest is v3.0.0

![Screenshot 2022-02-11 223423](https://user-images.githubusercontent.com/140737/153698484-356d3e7e-3de4-4ad9-9c4d-8e695fbad8c5.png)

**Comment by spakin** [comment]
I believe this relates to Inkscape issue [#2822](https://gitlab.com/inkscape/inkscape/-/issues/2822) and to the workaround that Simple Inkscape Scripting put in place to address issue #25, which reports what looks like a very similar error message.

As @peterennis suggests, you should make sure you're running a recent version of Simple Inkscape Scripting.  Either download the latest release from the [releases page](https://github.com/spakin/SimpInkScr/releases) or clone the GitHub repository.

**Comment by spakin** [comment]
Great!  Thanks for following up.
